language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy3"

env:
  - WITH_PYGMENTS=0
  - WITH_PYGMENTS=1

matrix:
  exclude:
    # pygment does not support Python 3.4
    - python: "3.4"
      env: WITH_PYGMENTS=1
  allow_failures:
    - python: "nightly"

install:
  - pip install -r dev-requirements.txt
  - if [[ $WITH_PYGMENTS -eq 1 ]]; then pip install pygments; fi
  - pip install .

script:
  - coverage run test.py

after_success:
  - codecov
  - coveralls
